# Generated by Django 5.1.6 on 2025-10-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_lease_source_application_lease_source_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tenants.installment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reciept_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tenants.utility'),
        ),
    ]
