# Generated by Django 5.1.6 on 2025-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_payment_installement_payment_reciept_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reciept_file',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
