# Generated by Django 5.1.6 on 2025-10-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_payment_reciept_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reciept_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
