# Generated by Django 5.1.6 on 2025-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_payment_reciept_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='holding_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Holding fee amount from agreement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent amount from agreement', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('pending_verification', 'Pending Verification'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
