# Generated by Django 5.1.6 on 2025-11-03 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_payment_reciept_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('configured', 'Payment Configured'), ('confirmed', 'Confirmed')], default='pending', max_length=30)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='direct_debit_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectDebitUtility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('configured', 'Payment Configured'), ('confirmed', 'Confirmed')], default='pending', max_length=30)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='direct_debit_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='utility',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('pending_verification', 'Pending Verification'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='direct_debit_installment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_for_installment', to='tenants.directdebitinstallment'),
        ),
        migrations.AddField(
            model_name='lease',
            name='direct_debit_utility',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_for_utility', to='tenants.directdebitutility'),
        ),
    ]
