# Generated by Django 5.1.6 on 2025-11-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_directdebitinstallment_directdebitutility_and_more'),
        ('tenants', '0006_lease_holding_fee_lease_monthly_rent_and_more'),
    ]

    operations = [
    ]
