# Generated by Django 5.1.6 on 2025-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_merge_20251103_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='holding_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Holding fee amount from application bond amount', max_digits=10, null=True),
        ),
    ]
