# Generated by Django 5.1.6 on 2025-08-17 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_chat', models.BooleanField(default=True)),
                ('email_lease', models.BooleanField(default=True)),
                ('email_maintenance', models.BooleanField(default=True)),
                ('email_inspection', models.BooleanField(default=True)),
                ('email_payment', models.BooleanField(default=True)),
                ('inapp_notifications', models.BooleanField(default=True)),
                ('inapp_chat', models.BooleanField(default=True)),
                ('inapp_lease', models.BooleanField(default=True)),
                ('inapp_maintenance', models.BooleanField(default=True)),
                ('inapp_inspection', models.BooleanField(default=True)),
                ('inapp_payment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('chat', 'Chat Message'), ('lease_request', 'Lease Request'), ('lease_approval', 'Lease Approval'), ('lease_rejection', 'Lease Rejection'), ('maintenance_request', 'Maintenance Request'), ('maintenance_update', 'Maintenance Update'), ('inspection_schedule', 'Inspection Scheduled'), ('inspection_update', 'Inspection Update'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('property_approval', 'Property Approval'), ('property_rejection', 'Property Rejection'), ('agent_request', 'Agent Request'), ('general', 'General Notification')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
