# Generated by Django 5.1.6 on 2026-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'Chat Message'), ('lease_request', 'Lease Request'), ('lease_approval', 'Lease Approval'), ('lease_rejection', 'Lease Rejection'), ('maintenance_request', 'Maintenance Request'), ('maintenance_update', 'Maintenance Update'), ('inspection_schedule', 'Inspection Scheduled'), ('inspection_update', 'Inspection Update'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('property_approval', 'Property Approval'), ('property_rejection', 'Property Rejection'), ('agent_request', 'Agent Request'), ('account_suspension', 'Account Suspension'), ('account_reactivation', 'Account Reactivation'), ('removal_warning', 'Account Removal Warning'), ('account_deleted', 'Account Deleted'), ('account_restored', 'Account Restored'), ('general', 'General Notification'), ('reels', 'Reels'), ('marketplace', 'Marketplace'), ('offers', 'Offers')], default='general', max_length=50),
        ),
    ]
