# Generated by Django 5.1.6 on 2025-04-12 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('electricity_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('broadband_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tv_license_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('avalible_after', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('key_features', models.JSONField(blank=True, null=True)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('holding_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('epc_rating', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Average'), ('E', 'E - Poor'), ('F', 'F - Very Poor'), ('G', 'G - Extremely Poor')], default='C', max_length=1)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bills_included', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented_out', 'Rented Out'), ('pending', 'Pending'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.city')),
                ('land_lord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.tax')),
                ('universities', models.ManyToManyField(to='properties.university')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
