# Generated by Django 5.1.6 on 2025-03-17 17:44

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "universities_updated.json",
        app_label="properties",
    )


def unload_initial_data(apps, schema_editor):
    UniversityModel = apps.get_model("properties", "University")
    UniversityModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_auto_20250317_1744"),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
