# Generated by Django 5.1.6 on 2025-06-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20250317_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.AddField(
            model_name='property',
            name='area_index',
            field=models.IntegerField(default=1, help_text='Index of the area within the selected city (0-based)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='city_index',
            field=models.IntegerField(default=1, help_text='Index of the city in the frontend locations array (0-based)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
