# Generated by Django 5.1.6 on 2025-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='property',
            name='electric_expiry_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gas_expiry_date',
        ),
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True, help_text='Property availability status'),
        ),
        migrations.AddField(
            model_name='property',
            name='electric_from_date',
            field=models.DateField(blank=True, help_text='Electrical safety certificate start date', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electric_to_date',
            field=models.DateField(blank=True, help_text='Electrical safety certificate expiry date', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_from_date',
            field=models.DateField(blank=True, help_text='Gas safety certificate start date', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_to_date',
            field=models.DateField(blank=True, help_text='Gas safety certificate expiry date', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bills_included',
            field=models.BooleanField(default=True, editable=False, help_text='Bills are always included'),
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
