# Generated by Django 5.1.6 on 2025-03-17 17:44

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    # No need to load area fixture anymore as the Area model has been removed
    pass


def unload_initial_data(apps, schema_editor):
    # Area model has been removed, no need to clean up
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
