# Generated by Django 5.1.6 on 2025-06-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_city_area_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='avalible_after',
            new_name='available_after',
        ),
    ]
