# Generated by Django 5.1.6 on 2025-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_avalible_after_property_available_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electric_expiry_date',
            field=models.DateField(blank=True, help_text='Electrical safety certificate expiry date', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_expiry_date',
            field=models.DateField(blank=True, help_text='Gas safety certificate expiry date', null=True),
        ),
    ]
