# Generated by Django 5.1.6 on 2025-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_avalible_after_property_available_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='utility_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=10, null=True),
        ),
    ]
