# Generated by Django 5.1.6 on 2025-08-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_electric_expiry_date_and_more'),
        ('properties', '0007_property_utility_amount'),
    ]

    operations = [
    ]
