# Generated by Django 5.1.6 on 2025-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_tax_add_certificate_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='available',
        ),
        migrations.AddField(
            model_name='property',
            name='available_to',
            field=models.DateField(blank=True, help_text='Property available until date', null=True),
        ),
    ]
