# Generated by Django 5.1.6 on 2025-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_add_available_to_remove_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Agent's original price before commission", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Final price shown to users (including commission)', max_digits=10),
        ),
    ]
