# Generated by Django 5.1.6 on 2025-10-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0012_add_base_price_for_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('home_address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('current_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_email', models.EmailField(max_length=254)),
                ('rent_payer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], max_length=10)),
                ('how_heard', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_check', models.CharField(choices=[('Default', 'Default'), ('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Default', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount_of_bond', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('nic', models.ImageField(blank=True, null=True, upload_to='nic/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('agent', models.CharField(max_length=200)),
                ('agent_address', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('land_lord_sign', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('lead_tenant_sign', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('lls_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreementform', to='forms.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.TextField()),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('years', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('job_title', models.CharField(max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_details', to='forms.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('work_address', models.TextField()),
                ('time_at_address', models.CharField(max_length=100)),
                ('previous_address', models.TextField(blank=True, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_address', models.TextField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('proof_of_employment', models.ImageField(blank=True, null=True, upload_to='proof_of_employment/')),
                ('guarantor_sign', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('g_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('gs_date', models.DateField(blank=True, null=True)),
                ('witness_sign', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('ws_date', models.DateField(blank=True, null=True)),
                ('ws_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_check', models.CharField(choices=[('Default', 'Default'), ('Pass', 'Pass'), ('Default', 'Default'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Default', max_length=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantorform', to='forms.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('Tenant', 'Tenant'), ('Guarantor', 'Guarantor'), ('Landlord', 'Landlord'), ('Witness', 'Witness')], max_length=10)),
                ('signed', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('work_name', models.CharField(max_length=100)),
                ('work_address', models.TextField()),
                ('work_postcode', models.CharField(max_length=10)),
                ('work_phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_details', to='forms.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousLandlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('property_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_beds', models.IntegerField(blank=True, null=True)),
                ('current_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bond', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_landlord', to='forms.applicationform')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('current_year', models.IntegerField()),
                ('nin', models.CharField(max_length=100)),
                ('loan_recieved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='forms.applicationform')),
            ],
        ),
        migrations.CreateModel(
            name='TenantSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('sign', models.ImageField(upload_to='signatures/')),
                ('date', models.DateField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_signs', to='forms.agreementform')),
            ],
        ),
    ]
