# Generated by Django 5.1.6 on 2025-10-11 08:06

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_applicationform_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='nic',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.application_nic_path),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.application_signature_path),
        ),
        migrations.AlterField(
            model_name='guarantorform',
            name='guarantor_sign',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.guarantor_signature_path),
        ),
        migrations.AlterField(
            model_name='guarantorform',
            name='proof_of_employment',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.proof_of_employment_path),
        ),
        migrations.AlterField(
            model_name='guarantorform',
            name='witness_sign',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.witness_signature_path),
        ),
        migrations.AlterField(
            model_name='tenantsigns',
            name='sign',
            field=models.ImageField(upload_to=forms.models.tenant_signature_path),
        ),
    ]
