# Generated by Django 5.1.6 on 2025-10-11 08:18

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_applicationform_nic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementform',
            name='land_lord_sign',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.landlord_signature_path),
        ),
    ]
