# Generated by Django 5.1.6 on 2025-10-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_guarantorform_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='agent_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreementform',
            name='filled_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementform',
            name='tenant_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='agent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementform',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
