# Generated by Django 5.1.6 on 2025-10-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_agreementform_agent_filled_and_more'),
        ('tenants', '0002_lease_source_application_lease_source_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='tenants.inquiries'),
        ),
    ]
