# Generated by Django 5.1.6 on 2025-10-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_agreementform_admin_filled_agreementform_admin_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='admin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
