# Generated by Django 5.1.6 on 2025-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_add_step_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
