# Generated by Django 5.1.6 on 2025-03-02 17:22

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.create(name="admin")
    Group.objects.create(name="landlord")
    Group.objects.create(name="tenant")


def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=["admin", "landlord", "tenant"]).delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
