# Generated by Django 5.1.6 on 2025-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
