# Generated by Django 5.1.6 on 2025-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_guarantorsharetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantorform',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
