# Generated by Django 5.1.6 on 2025-10-15 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_applicationform_inquiry'),
        ('tenants', '0002_lease_source_application_lease_source_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forms', to='tenants.inquiries'),
        ),
    ]
