# Generated by Django 5.1.6 on 2025-10-29 17:03

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_applicationform_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementform',
            name='admin_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreementform',
            name='admin_sign',
            field=models.ImageField(blank=True, null=True, upload_to=forms.models.admin_signature_path),
        ),
        migrations.AddField(
            model_name='agreementform',
            name='admin_sign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
