# Generated by Django 5.1.6 on 2025-11-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_multi_tenant_agreement_support'),
        ('forms', '0011_agreementform_admin_name'),
    ]

    operations = [
    ]
