# Generated by Django 5.1.6 on 2025-10-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_agreementform_agent_filled_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='source_application',
            field=models.ForeignKey(blank=True, help_text='The application form this lease was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_created', to='forms.applicationform'),
        ),
        migrations.AddField(
            model_name='lease',
            name='source_inquiry',
            field=models.ForeignKey(blank=True, help_text='The inquiry this lease originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_created', to='tenants.inquiries'),
        ),
    ]
