# Generated by Django 5.1.6 on 2025-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_agent_landlord_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bin_date',
            field=models.DateTimeField(blank=True, help_text='Date when user was moved to bin status', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('binned', 'Binned'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
