# Generated by Django 5.1.6 on 2025-10-02 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_update_agent_landlord_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='Landlord address', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for landlord', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by_agent',
            field=models.ForeignKey(blank=True, help_text='Agent who created this landlord', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_landlords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the landlord', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], help_text='Preferred contact method', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sort_code',
            field=models.CharField(blank=True, help_text='Bank sort code', max_length=8, null=True),
        ),
    ]
